version: '3.1'
services:
  odoo:
    image: odoo:${ODOO_VERSION}
    depends_on:
      - odoo-db
    ports:
      - "${HOST_PORT}:8069"
      - "${LONGPOLLING_PORT}:8072"
    volumes:
      - type: bind
        source: /c/repos/data/odoo/${DATABASE_NAME}/odoo
        target: /var/data/odoo
      - ./conf:/etc/odoo
      - ./third_party_addons:/mnt/extra-addons
    environment:
      - HOST=odoo-db
      - PORT=5432
      - USER=usr_odoo
      - PASSWORD=Q37zfHgsswMnYQnKPZG4XQ5p
      - DATABASE_NAME=${DATABASE_NAME}
      # - ODOO_INITIAL_MODULES=base,billing_do,billing_do_ce,professional_templates,account_statement_base,accounting_pdf_reports,account_oca_reconcile,base_account_budget,base_accounting_kit,gsk_automatic_mail_server,om_account_bank_statement_import,om_account_daily_reports,om_account_followup,om_dynamic_reports,om_fiscal_year,om_recurring_payment
    secrets:
      - postgresql_password
    extra_hosts:
      - "odoo-host:host-gateway"
    entrypoint:
      - /entrypoint.sh
      - --init
      - billing_do, billing_do_ce, professional_templates
      - --update
      - billing_do, billing_do_ce, kcs_medical_app, ars_do, professional_templates
      - --addons-path
      - ${ADDONS_PATH}
  odoo-db:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=usr_odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - type: bind
        source: /c/repos/data/odoo/portafolio-do-ce/pgdata
        target: /var/lib/postgresql/data/pgdata
      - type: bind
        source: /c/repos/data/production-backups/${DATABASE_NAME}/
        target: /var/data/backups
    secrets:
      - postgresql_password

secrets:
  postgresql_password:
    file: odoo_pg_pass
