version: '3.1'
services:
  odoo-ee:
    image: odoo:13.0
    depends_on:
      - odoo-db
    ports:
      - "${ENV_HOST_PORT}:8069"
    volumes:
      - type: bind
        source: /var/data/${ENV_DATABASE_NAME}/odoo
        target: /var/data/odoo
      - ./conf-dev:/etc/odoo
      - ./third_party_addons:/mnt/extra-addons
      - /opt/odoo/enterprise:/opt/odoo/enterprise
    environment:
      - HOST=odoo-db
      - USER=usr_odoo
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
    extra_hosts:
      - "odoo-host:host-gateway"
    entrypoint:
      - /entrypoint.sh
      - --init
      - web_environment_ribbon, billing_do, billing_do_ee, professional_templates
      - --update
      - billing_do, billing_do_ee, kcs_medical_app, ars_do, professional_templates
  odoo-db:
    image: postgres:13
    ports:
      - "${ENV_DATABASE_PORT}:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=usr_odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - type: bind
        source: /var/data/${ENV_DATABASE_NAME}/pgdata
        target: /var/lib/postgresql/data/pgdata
      - type: bind
        source: /var/data/production-backups/${ENV_DATABASE_NAME}/
        target: /var/data/backups
    secrets:
      - postgresql_password

secrets:
  postgresql_password:
    file: odoo_pg_pass
